config/routes.rb
Rails.application.routes.draw do
  # Topページ
  root to: 'tops#index'

  # ログイン
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # ユーザー登録
  resources :users, only: [:new, :create, :show, :edit, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  add_flash_types :success, :danger

  private

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top; end
  
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: t('user_sessions.create.success')
    else
      flash.now[:danger] = t('user_sessions.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: t('user_sessions.destroy.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: t('users.create.success')
    else
      flash.now[:danger] = t('users.create.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="bg-base-300">
  <div class="navbar">
    <div class="navbar-start">
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </div>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <a>投稿</a>
            <ul class="p-2">
              <li><a>一覧</a></li>
              <li><a>新規投稿</a></li>
            </ul>
          </li>
          <li><a>ブックマーク一覧</a></li>
        </ul>
      </div>
      <%= link_to 'アプリ名', root_path, class: 'btn btn-ghost text-xl' %>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li>
          <details>
            <summary>投稿</summary>
            <ul class="p-2">
              <li><a>一覧</a></li>
              <li><a>新規投稿</a></li>
            </ul>
          </details>
        </li>
        <li><a></a></li>
        <li><a>ブックマーク一覧</a></li>
      </ul>
    </div>

      <div class="navbar-end">
        <div class="form-control">
          <input type="text" placeholder="Search" class="input input-bordered w-24 md:w-auto" />
        </div>
        <div class="">
          <%= link_to t('header.logout'), login_path, class:"btn btn-outline btn-info ml-3" %>
        </div>
      </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer items-center p-4 bg-neutral text-neutral-content">
  <aside class="items-center grid-flow-col">
    <svg width="36" height="36" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
    <p>Copyright © 2024 - All right reserved</p>
  </aside>
  <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
    <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg>
    </a>
    <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path></svg></a>
    <a><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current"><path d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path></svg></a>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="bg-base-300">
  <div class="navbar">
    <div class="navbar-start">
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </div>
        <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <%= link_to t('header.logout'), logout_path, data: { turbo_method: :delete } %>
            <a>投稿</a>
            <ul class="p-2">
              <li><a>一覧</a></li>
              <li><a>新規投稿</a></li>
            </ul>
          </li>
          <li><a>ブックマーク一覧</a></li>
        </ul>
      </div>
      <%= link_to 'アプリ名', root_path, class: 'btn btn-ghost text-xl' %>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li>
          <details>
            <summary>投稿</summary>
            <ul class="p-2">
              <li><a>一覧</a></li>
              <li><a>新規投稿</a></li>
            </ul>
          </details>
        </li>
        <li><a></a></li>
        <li><a>ブックマーク一覧</a></li>
      </ul>
    </div>

      <div class="navbar-end">
        <div class="form-control">
          <input type="text" placeholder="Search" class="input input-bordered w-24 md:w-auto" />
        </div>
        <div class="dropdown dropdown-end">
          <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
            <div class="w-10 rounded-full">
              <img alt="Tailwind CSS Navbar component" src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
            </div>
          </div>
          <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
            <li>
              <a class="justify-between">
                Mypage
                <span class="badge">New</span>
              </a>
            </li>
            <li><%= current_user.decorate.full_name %></li>
            <li><%= link_to t('header.logout'), logout_path, data: { turbo_method: :delete } %></li>
          </ul>
        </div>
      </div>
  </div>
</header>

app/views/tops/index.html.erb
<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>

app/views/user_sessions/new.html.erb
<%# ログインページ %>
<div class="flex justify-center">
  <%= form_with url: login_path do |f| %>
    <label class="input input-bordered flex items-center my-5">
      <%= f.email_field :email, class:"grow", placeholder: t('activerecord.attributes.user.email')  %>
    </label>

    <label class="input input-bordered flex items-center my-5">
      <%= f.password_field :password, class: "grow", placeholder: t('activerecord.attributes.user.password')  %>
    </label>

    <div class="flex justify-center w-full">
      <%= f.submit t('.login'), class:"btn btn-outline btn-info my-3" %>
    </div>
  <% end %>
</div>
  <div class="flex justify-center my-3">
    <%= link_to t('.to_register_page'), new_user_path, class: "link link-primary" %>
  </div>

app/views/users/new.html.erb
<%# ユーザー登録ページ %>
<div class="flex justify-center">
  <%= form_with model: @user do |f| %>
      <label class="input input-bordered flex items-center my-3">
      <%= f.text_field :last_name, class:"grow", placeholder: t('activerecord.attributes.user.last_name')%>
    </label>

    <label class="input input-bordered flex items-center my-3">
      <%= f.text_field :first_name, class:"grow", placeholder: t('activerecord.attributes.user.first_name')%>
    </label>

    <label class="input input-bordered flex items-center my-3">
      <%= f.email_field :email, class:"grow", placeholder: t('activerecord.attributes.user.email') %>
    </label>

    <label class="input input-bordered flex items-center my-3">
      <%= f.password_field :password, class: "grow", placeholder: t('activerecord.attributes.user.password') %>
    </label>

    <label class="input input-bordered flex items-center my-3">
      <%= f.password_field :password_confirmation, class: "grow", placeholder: t('activerecord.attributes.user.password_confirmation')  %>
    </label>

    <div class="flex justify-center w-full">
      <%= f.submit t('.create'), class:"btn btn-outline btn-info my-3" %>
    </div>
  <% end %>
</div>
<div class="flex justify-center my-3">
  <%= link_to t('.to_login_page'), login_path, class: "link link-primary" %>
</div>